hydra:
  job:
    name: ${exp.name}
  run:
    dir: '${exp.outdir}/${exp.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
  sweep:
    dir: ${exp.outdir}/${exp.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.id}_${hydra:job.override_dirname}

exp:
  outdir: out
  name: ABSESpy
  repeats: 1
  logging: once
