
version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s"
    datefmt: '%H:%M:%S'
  project:
    format: "[%(asctime)s] %(levelname)s %(message)s"
    datefmt: '%H:%M:%S'

handlers:
  console:  # handler which will log into stdout
    class: logging.StreamHandler
    level: WARN
    formatter: standard  # Use formatter defined above
    stream: ext://sys.stdout
  warn:  # handler which will log into file
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: standard  # Use formatter defined above
    filename: logs/warnings.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8
  debug:  # handler which will log into file
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: project  # Use formatter defined above
    filename: logs/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

root:  # Loggers are organized in hierarchy - this is the root logger config
  level: INFO
  handlers: [console, warn, debug]  # Attaches both handler defined above
